name: sample_todo_app
description: A sample TODO Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '3.2.3'

dependencies:
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  path:
  path_provider: ^2.1.0
  sembast: ^3.5.0+1
  shared_preferences: ^2.1.2
  riverpod_lint: ^2.3.2
  http: ^1.1.2
  intl: ^0.19.0
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.9.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true